/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        skapa: {
          'neutral-1': 'var(--skapa-neutral-1)',
          'neutral-2': 'var(--skapa-neutral-2)',
          'neutral-3': 'var(--skapa-neutral-3)',
          'neutral-4': 'var(--skapa-neutral-4)',
          'neutral-5': 'var(--skapa-neutral-5)',
          'neutral-6': 'var(--skapa-neutral-6)',
          'neutral-7': 'var(--skapa-neutral-7)',
          'text-1': 'var(--skapa-text-1)',
          'text-2': 'var(--skapa-text-2)',
          'text-3': 'var(--skapa-text-3)',
          'text-4': 'var(--skapa-text-4)',
          'text-5': 'var(--skapa-text-5)',
          'elevation-1': 'var(--skapa-elevation-1)',
          'elevation-2': 'var(--skapa-elevation-2)',
          'elevation-border-1': 'var(--skapa-elevation-border-1)',
          'elevation-border-2': 'var(--skapa-elevation-border-2)',
          'positive': 'var(--skapa-positive)',
          'negative': 'var(--skapa-negative)',
          'caution': 'var(--skapa-caution)',
          'informative': 'var(--skapa-informative)',
          'brand-blue': 'var(--skapa-brand-blue)',
          'brand-yellow': 'var(--skapa-brand-yellow)',
          'static-white': 'var(--skapa-static-white)',
          'static-black': 'var(--skapa-static-black)',
          'static-grey': 'var(--skapa-static-grey)',
          'static-dark-grey': 'var(--skapa-static-dark-grey)',
          'static-light-grey': 'var(--skapa-static-light-grey)',
        },
      },
      borderRadius: {
        'skapa-s': 'var(--skapa-radius-s)',
        'skapa-m': 'var(--skapa-radius-m)',
        'skapa-l': 'var(--skapa-radius-l)',
      },
      spacing: {
        'skapa-25': 'var(--skapa-space-25)',
        'skapa-50': 'var(--skapa-space-50)',
        'skapa-75': 'var(--skapa-space-75)',
        'skapa-100': 'var(--skapa-space-100)',
        'skapa-150': 'var(--skapa-space-150)',
        'skapa-200': 'var(--skapa-space-200)',
        'skapa-300': 'var(--skapa-space-300)',
      },
    },
  },
  plugins: [],
};
